export const  ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const  ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const  ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"
export const  ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const  ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST"
export const  ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS"
export const  ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL"
export const  ADD_SERVICE = "ADD_SERVICE"

export const  DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST"
export const  DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS"
export const  DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL"
export const  DELETE_SERVICE = "DELETE_SERVICE"

export const  UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST"
export const  UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS"
export const  UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL"
export const  UPDATE_SERVICE = "UPDATE_SERVICE"

export const  ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST"
export const  ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS"
export const  ADD_LOCATION_FAIL = "ADD_LOCATION_FAIL"
export const  ADD_LOCATION = "ADD_LOCATION"

export const  DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST"
export const  DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS"
export const  DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL"
export const  DELETE_LOCATION = "DELETE_LOCATION"

export const  DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const  DELETE_USER_FAIL = "DELETE_USER_FAIL"
export const  DELETE_USER = "DELETE_USER"

export const  GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const  GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const  GET_USERS_FAIL = "GET_USERS_FAIL"

export const  GET_ADMIN_SERVICES_REQUEST = "GET_ADMIN_SERVICES_REQUEST"
export const  GET_ADMIN_SERVICES_SUCCESS = "GET_ADMIN_SERVICES_SUCCESS"
export const  GET_ADMIN_SERVICES_FAIL = "GET_ADMIN_SERVICES_FAIL"

export const  GET_ADMIN_LOCATION_REQUEST = "GET_ADMIN_LOCATION_REQUEST"
export const  GET_ADMIN_LOCATION_SUCCESS = "GET_ADMIN_LOCATION_SUCCESS"
export const  GET_ADMIN_LOCATION_FAIL = "GET_ADMIN_LOCATION_FAIL"
