export const  GET_SELLER_ORDERS_REQUEST = "GET_SELLER_ORDERS_REQUEST"
export const  GET_SELLER_ORDERS_SUCCESS = "GET_SELLER_ORDERS_SUCCESS"
export const  GET_SELLER_ORDERS_FAIL = "GET_SELLER_ORDERS_FAIL"

export const  GET_CLIENT_ORDERS_REQUEST = "GET_CLIENT_ORDERS_REQUEST"
export const  GET_CLIENT_ORDERS_SUCCESS = "GET_CLIENT_ORDERS_SUCCESS"
export const  GET_CLIENT_ORDERS_FAIL = "GET_CLIENT_ORDERS_FAIL"

export const  ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST"
export const  ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS"
export const  ADD_ORDER_FAIL = "ADD_ORDER_FAIL"
export const  ADD_ORDER = "ADD_ORDER"

export const  ADD_RATING_REQUEST = "ADD_RATING_REQUEST"
export const  ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS"
export const  ADD_RATING_FAIL = "ADD_RATING_FAIL"

export const  UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const  UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const  UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
export const  UPDATE_ORDER = "UPDATE_ORDER"

