
export const  GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const  GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const  GET_SERVICES_FAIL = "GET_SERVICES_FAIL"

export const  GET_TOPTEN_REQUEST = "GET_TOPTEN_REQUEST"
export const  GET_TOPTEN_SUCCESS = "GET_TOPTEN_SUCCESS"
export const  GET_TOPTEN_FAIL = "GET_TOPTEN_FAIL"

export const  GET_TOPFOUR_REQUEST = "GET_TOPFOUR_REQUEST"
export const  GET_TOPFOUR_SUCCESS = "GET_TOPFOUR_SUCCESS"
export const  GET_TOPFOUR_FAIL = "GET_TOPFOUR_FAIL"

export const  GET_BY_SERVICE_REQUEST = "GET_BY_SERVICE_REQUEST"
export const  GET_BY_SERVICE_SUCCESS = "GET_BY_SERVICE_SUCCESS"
export const  GET_BY_SERVICE_FAIL = "GET_BY_SERVICE_FAIL"

export const  GET_LOCATIONS_REQUEST = "GET_LOCATIONS_REQUEST"
export const  GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS"
export const  GET_LOCATIONS_FAIL = "GET_LOCATIONS_FAIL"

export const  GET_SELLER_SERVING_REQUEST = "GET_SELLER_SERVING_REQUEST"
export const  GET_SELLER_SERVING_SUCCESS = "GET_SELLER_SERVING_SUCCESS"
export const  GET_SELLER_SERVING_FAIL = "GET_SELLER_SERVING_FAIL"


export const  ADD_SERVING = "ADD_SERVING"
export const  DELETE_SERVING = "DELETE_SERVING"
export const  UPDATE_SERVING = "UPDATE_SERVING"

export const  ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST"
export const  ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS"
export const  ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL"

export const  DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST"
export const  DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS"
export const  DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL"

export const  UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST"
export const  UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS"
export const  UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL"

export const  GET_ONE_SERVICE_REQUEST = "GET_ONE_SERVICE_REQUEST"
export const  GET_ONE_SERVICE_SUCCESS = "GET_ONE_SERVICE_SUCCESS"
export const  GET_ONE_SERVICE_FAIL = "GET_ONE_SERVICE_FAIL"

export const  SEARCH_REQUEST = "SEARCH_REQUEST"
export const  SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const  SEARCH_FAIL = "SEARCH_FAIL"