export const  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const  USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const  USER_LOGOUT = "USER_LOGOUT"

export const  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const  USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const  USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const  USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const  USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const  UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const  UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const  UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

export const  UPDATE_INFO_REQUEST = "UPDATE_INFO_REQUEST"
export const  UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS"
export const  UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL"

export const  UPDATE_PERSONAL_IMAGE_REQUEST = "UPDATE_PERSONAL_IMAGE_REQUEST"
export const  UPDATE_PERSONAL_IMAGE_SUCCESS = "UPDATE_PERSONAL_IMAGE_SUCCESS"
export const  UPDATE_PERSONAL_IMAGE_FAIL = "UPDATE_PERSONAL_IMAGE_FAIL"


export const  CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const  CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const  CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"
 
export const  SEND_ACTIVATION_REQUEST = "SEND_ACTIVATION_REQUEST"
export const  SEND_ACTIVATION_SUCCESS = "SEND_ACTIVATION_SUCCESS"
export const  SEND_ACTIVATION_FAIL = "SEND_ACTIVATION_FAIL"
 
export const  DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST"
export const  DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"
export const  DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL"